import Head from 'next/head'
import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import Header from '../components/Header'

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.app}>
      <Head>
        <title>Top 10 Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://impala.in/wp-content/uploads/2020/04/cropped-cropped-cropped-logo-impala-32x32.png" sizes="32x32"></link>
      </Head>

      <main className={styles.main}>
        <Header />

        <div className={styles.body}>
          <Component {...pageProps} />
        </div>
      </main>

      <Footer />
    </div>
  );
}

export default MyApp
